Oglmodel
SofaDefrost/STLIB pull request #59
Opened 2021-08-13 12:32 UTC by CorentinLanguepin

Finalizing with changes mostly on scene and contactheader

2021-09-18 10:29 UTC, damienmarchal commented
Hi @Younesssss and @CorentinLanguepin 

Thanks for the PR. 
I do not merge it directly as this is currently part of a larger process composed:
- adding to SofaPython3 the missing functions to smooth the step between sofapython & sofapython3
- split what was in STLIB in two libraries : 
     - SPLIB:
     - STLIB: 
- For both libraries, adding unittest so that can be integrated into the sofa CI stack.
- For each library have a:
    - SPLIB/splib and SPLIB/splib3, 
    - STLIB/stlib and STLIB/stlib3, 
splib/stlib will focus on implementing exactly the same feature as before but on top of SofaPython3 while the  
splib3/stlib3 version will be focused on providing new features or alternative design using the new special features of SofaPython3. 
The underlying idea of all that is to maximize the backward compatibility.

2021-10-04 08:18 UTC, EulalieCoevoet commented
Hi Damien, 

As you said this is a large process and a work in progress. Meanwhie, some of us are using the branch `sofaPython3` as a temporary solution to have things working. 

This PR is actually to merge the work of Corentin into the branch `sofaPython3`, and I don't see why we souldn't. 
I'll start to review the changes if it's okay with you.

2021-10-04 08:38 UTC, EulalieCoevoet requested changes

2021-10-04 08:38 UTC, EulalieCoevoet commented on python3/src/stlib3/physics/rigid/RigidObject.py
> +                collisionGroup='0',
I think the default behavior is "everything can collide", so 0 is not a good default value. I'll change that.

2021-10-04 08:38 UTC, EulalieCoevoet commented on python3/src/stlib3/physics/rigid/RigidObject.py
> +        #object.addObject('CGLinearSolver')
I'm not sure why this has been removed? @CorentinLanguepin @Younesssss 
same for the `RequiredPlugin`.

2021-10-04 08:38 UTC, EulalieCoevoet commented on python3/src/stlib3/physics/rigid/RigidObject.py
> +    #scene.Simulation.addChild(rigid)
A reminder to remove the print.

2021-10-04 08:38 UTC, EulalieCoevoet commented on python3/src/stlib3/scene/contactheader.py
> +def ContactHeader(rootNode, alarmDistance, contactDistance, frictionCoef=0.0):
I like `applyTo` better, as it mean something.

2021-10-04 08:38 UTC, EulalieCoevoet commented on python3/src/stlib3/scene/contactheader.py
> +            rootNode.addObject('SparseLDLSolver')
I think it still should be `GenericConstraintSolver` and not `SparseLDLSolver`, those are completely different solvers.

2021-10-04 08:38 UTC, EulalieCoevoet commented on python3/src/stlib3/scene/scene.py
> +                nodeToParse='@./RigidifiedStructure/DeformableParts/ElasticMaterialObject')
This is not generic at all...

2021-10-04 08:38 UTC, EulalieCoevoet commented on python3/src/stlib3/visuals/visualmodel.py
> +    #scene.Modelling.init()
to remove

2021-10-04 09:28 UTC, EulalieCoevoet commented
I've made the changes and tested them. It's all good for me.

2021-10-05 18:09 UTC, merged